import { PowerInfo, PowerType } from '../types/game';

export const POWERS: Record<PowerType, PowerInfo> = {
  laser: {
    id: 'laser',
    key: '1',
    name: 'Kuantum Işık Kılıcı',
    turkishName: 'Işık Kılıcı',
    element: 'Foton & Lazer',
    description: 'Keskin enerji dalgasıyla düşmanları ortadan ikiye pürüzsüzce keser, kristal kıvılcımlar saçar.',
    primaryAttackName: 'Işık Kesişi',
    ultimateName: 'Boyut Yarığı (Omni-Slash)',
    color: '#00F0FF',
    glowColor: 'rgba(0, 240, 255, 0.7)',
    hexColor: 0x00f0ff,
    emissiveHex: 0x00a8ff,
    lightHex: 0x38bdf8,
    bladeColor: '#38bdf8',
    icon: 'Sword',
    cooldownMs: 250,
    ultimateCost: 100,
    damage: 120,
    sliceEffect: 'Pürüzsüz Kristal Dilimi',
  },
  fire: {
    id: 'fire',
    key: '2',
    name: 'Kozmik Güneş Ateşi',
    turkishName: 'Güneş Ateşi',
    element: 'Plazma & Termal',
    description: 'Akkor güneş alevleri fırlatarak hedefleri kavurucu altın kıvılcımlar ve şok dalgalarıyla patlatır.',
    primaryAttackName: 'Ateş Patlaması',
    ultimateName: 'Süpernova Çöküşü',
    color: '#FF6B00',
    glowColor: 'rgba(255, 107, 0, 0.7)',
    hexColor: 0xff6b00,
    emissiveHex: 0xff3b00,
    lightHex: 0xfb923c,
    bladeColor: '#f97316',
    icon: 'Flame',
    cooldownMs: 350,
    ultimateCost: 100,
    damage: 160,
    sliceEffect: 'Erimiş Kor Patlaması',
  },
  frost: {
    id: 'frost',
    key: '3',
    name: 'Kristal Buz & Şarapnel',
    turkishName: 'Buz Parçalayıcı',
    element: 'Glasiyel & Kristal',
    description: 'Düşmanları anında dondurur ve buzdan heykellere çevirip yüzlerce parıldayan elmasa böler.',
    primaryAttackName: 'Buz Mızrağı & Dondurma',
    ultimateName: 'Mutlak Sıfır Kar Fırtınası',
    color: '#38BDF8',
    glowColor: 'rgba(56, 189, 248, 0.7)',
    hexColor: 0x7dd3fc,
    emissiveHex: 0x0284c7,
    lightHex: 0xbae6fd,
    bladeColor: '#7dd3fc',
    icon: 'Snowflake',
    cooldownMs: 300,
    ultimateCost: 100,
    damage: 100,
    sliceEffect: 'Pırlanta Kristal Parçalanması',
  },
  lightning: {
    id: 'lightning',
    key: '4',
    name: 'Zincirleme Plazma Yıldırımı',
    turkishName: 'Plazma Yıldırımı',
    element: 'Statik & Elektromanyetik',
    description: 'Mor ve camgöbeği elektrik arklarıyla düşmanlar arasında zıplayarak hepsini şok dalgasıyla yakar.',
    primaryAttackName: 'Yıldırım Arkı',
    ultimateName: 'Kıyamet Gök Gürültüsü',
    color: '#C084FC',
    glowColor: 'rgba(192, 132, 252, 0.7)',
    hexColor: 0xc084fc,
    emissiveHex: 0x9333ea,
    lightHex: 0xe879f9,
    bladeColor: '#c084fc',
    icon: 'Zap',
    cooldownMs: 280,
    ultimateCost: 100,
    damage: 140,
    sliceEffect: 'Mor Plazma İyonizasyonu',
  },
  void: {
    id: 'void',
    key: '5',
    name: 'Kara Delik & Zaman Bükümü',
    turkishName: 'Kara Delik',
    element: 'Kuantum & Çekim',
    description: 'Yerçekimi anomalisi yaratarak düşmanları kendine çeker, zamanı yavaşlatır ve derin basla ezer.',
    primaryAttackName: 'Mikro Tekillik',
    ultimateName: 'Krono Çöküşü (Zaman Durdurma)',
    color: '#818CF8',
    glowColor: 'rgba(129, 140, 248, 0.7)',
    hexColor: 0x818cf8,
    emissiveHex: 0x4f46e5,
    lightHex: 0x6366f1,
    bladeColor: '#818cf8',
    icon: 'Orbit',
    cooldownMs: 400,
    ultimateCost: 100,
    damage: 200,
    sliceEffect: 'Kozmik Çöküş & Bas Dalgası',
  },
};

export const POWER_LIST = Object.values(POWERS);
